<?php
// Simulate an admin receiving a notification
$db = new mysqli('localhost', 'root', '', 'db_monitoring_bpom');
if ($db->connect_error) {
    die("Connection failed: " . $db->connect_error);
}

// 1. Insert a dummy notification for perencana (user_id = 2)
$db->query("INSERT INTO notifications (user_id, title, message, link, is_read, created_at, updated_at) VALUES (2, 'Test Notification', 'This is a test notification generated by the verification script.', '/admin/dashboard', 0, NOW(), NOW())");

// 2. Fetch unread count for perencana
$result = $db->query("SELECT COUNT(*) as count FROM notifications WHERE user_id = 2 AND is_read = 0");
$row = $result->fetch_assoc();
echo "Unread notifications for perencana: " . $row['count'] . "\n";

// 3. Mark it as read
$db->query("UPDATE notifications SET is_read = 1 WHERE user_id = 2");

// 4. Fetch unread count again
$result = $db->query("SELECT COUNT(*) as count FROM notifications WHERE user_id = 2 AND is_read = 0");
$row = $result->fetch_assoc();
echo "Unread notifications for perencana after marking as read: " . $row['count'] . "\n";

?>
